name: Testing Moonspot\ValueObjects

on: [push, pull_request]

jobs:
  run:
    strategy:
      matrix:
        php-versions: ['8.0', '8.1', '8.2', '8.3']
        include:
          - operating-system: 'ubuntu-latest'
            php-versions: '8.0'
            phpunit-versions: 9
    test:
      runs-on: ubuntu-latest

      steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Composer Install
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php-versions }}

      - name: PHPUnit tests
        uses: php-actions/phpunit@v3
        with:
          php_extensions: "pcov"
          version: "9.6"
          php_version: ${{ matrix.php-versions }}
