name: Testing Moonspot\ValueObjects

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Composer Install
      uses: php-actions/composer@v6
      with:
        php_version: 8.0

    - name: PHPUnit tests
      uses: php-actions/phpunit@v3
      with:
        version: 9.6
        php_version: 8.0
